# ExpBottler by Fyrezz
# Report bugs @ https://github.com/Fyrezz/ExpBottler/issues
# Spigot resource link https://www.spigotmc.org/resources/expbottler-1-8-1-14-opensource.66288/

# You like it? Feel free to contact me
# for any custom plugin :) Fyrezz.3163

# Set the name for Magic Exp Bottles
# If you change it, old bottles won't work.
bottlename: '&b&lMagic Exp Bottle&7 (Right click!)'

# Minimum experience to create a Magic Bottle
minimumexperience: 100

# Maximum experience to create a Magic Bottle
# DON'T GO OVER 32,000
maximumexperience: 10000

# EXP removed as tax on bottle redeem
# Keep it positive
redeemtax: 5

# Permission to create Magic Bottles
# (/xpbottle)
xpbottlepermission: expbottler.xpbottle

# Permission to give Magic Bottles
# (/givexpbottle) - Keep this for admins
givexpbottlepermission: expbottler.givexpbottle