name: ExpBottler
description: Convert Experience into Magic Bottles and vice versa.
author: Fyrezz
website: https://github.com/Fyrezz/ExpBottler

main: net.fyrezz.me.expbottler.P
version: 0.0.1
api-version: 1.13

commands:
  xpbottle:
    description: Bottle your exp!
    aliases: [xpb, bottlexp, bottlexp, expbottle, expb]
  givexpbottle:
    description: Give an EXP Bottle to a player.
    aliases: [giveexpbottle, givexpb, giveexpb]
